config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  # Users
  devise_for :users, controllers: { passwords: "passwords" }, skip: :registrations
  resources :users do
    get 'enable', on: :member
    get 'disable', on: :member
    get 'deleted', on: :collection
    get 'restore', on: :member
  end

  resources :clients

  resources :movies do
    post 'return', action: :return_movie, on: :member
    get 'rent', on: :member
    put 'rent', action: :update_rent, on: :member
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy,:return_movie, :rent, :update_rent]
  before_action :set_default_form, only: [:edit, :new]

  add_breadcrumb "Inicio", :root_path
  add_breadcrumb "Películas", :movies_path

  # GET /movies
  # GET /movies.json
  def index
    add_breadcrumb "Listado"

    @movies = Movie.includes(:client, :category).order(name: :asc).all
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
    add_breadcrumb @movie.name
    add_breadcrumb "Detalles"
  end

  # GET /movies/new
  def new
    add_breadcrumb "Agregar"

    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
    add_breadcrumb @movie.name
    add_breadcrumb "Editar"
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'La película ha sido creada exitosamente.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'La película ha sido actualizada exitosamente.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /movies/1/rent
  def rent
    if @movie.client.nil?
      add_breadcrumb @movie.name
      add_breadcrumb "Rentar"

      @clients = Client.order(name: :asc)
    else
      respond_to do |format|
        format.html { redirect_to movies_url, notice: 'La Película ya estaba rentada.' }
        format.json { head :no_content }
      end
    end
  end

  # PUT /movies/1/rent
  def update_rent
    respond_to do |format|
      if @movie.client.nil?
        if @movie.update(client_id: movie_params[:client_id], rents: (@movie.rents + 1))
          @client = @movie.client

          @client.update(rents: (@client.rents + 1)) unless @client.nil?

          sales_force_service = SalesForceService.new
          sales_force_service.rented_movie(@movie)

          format.html { redirect_to @movie, notice: 'La película ha sido rentada exitosamente.' }
          format.json { render :show, status: :ok, location: @movie }
        else
          format.html { render :rent }
          format.json { render json: @movie.errors, status: :unprocessable_entity }
        end
      else
        format.html { redirect_to movies_url, notice: 'La Película ya estaba rentada.' }
        format.json { head :no_content }
      end
    end
  end

  def return_movie
    respond_to do |format|
      if @movie.update(client_id: nil)
        sales_force_service = SalesForceService.new
        sales_force_service.return_movie(@movie)

        format.html { redirect_to movies_url, notice: 'La película ha sido retornada exitosamente.' }
        format.json { head :no_content }
      else
        format.html { render :index }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'La película ha sido eliminada exitosamente.' }
      format.json { head :no_content }
    end
  end

  private
    def set_default_form
      @categories = Category.order(name: :asc)
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def movie_params
      params.require(:movie).permit(:name, :director, :email, :release_date, :category_id, :image, :client_id)
    end
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/movies/_form.html.erb
<%= form_for(movie) do |f| %>
  <%= render 'application/form_errors', form: movie %>

  <div class="form-group">
    <%= f.label :name, "Nombre", class: "control-label" %>
    <%= f.text_field :name, class: "form-control", data: { validation: 'required' }  %>
  </div>

  <div class="form-group">
    <%= f.label :director, "Director", class: "control-label" %>
    <%= f.text_field :director, class: "form-control", data: { validation: 'required' }  %>
  </div>

  <div class="form-group">
    <%= label_tag :category_id, "Categoría", class: "control-label" %>
    <%= f.collection_select :category_id, @categories, :id, :name, { include_blank: 'Seleccione una categoría', selected: (movie.category.id unless movie.category.nil?) }, { id: 'category-selector', class: 'form-control', data: { validation: 'required' } } %>
  </div>

  <div class="form-group">
    <%= f.label :release_date, "Fecha de Estreno", class: "control-label" %>
    <%= f.text_field :release_date, class: "datepicker form-control", data: { validation: 'date', "validation-format": "dd/mm/yyyy" } %>
  </div>

  <div class="row">
    <div class="col-sm-9">
      <%= f.file_field :image, class: 'form-control' %>
    </div>
    <div class="col-sm-3"><%= image_tag movie.image(:medium), class: 'img-responsive' %></div>
  </div>

  <div class="form-group">
    <%= f.submit "Guardar", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/movies/edit.html.erb
<div class="row">
  <div class="col-sm-12">
    <h1 class="page-header">Editar Película</h1>
  </div>
</div>

<div class="row">
  <div class="col-sm-6">
    <div class="panel panel-default">
      <div class="panel-body">
        <%= render 'form', movie: @movie %>
      </div>
    </div>
  </div>
</div>

app/views/movies/index.html.erb
<h1>Películas <%= link_to 'Agregar', new_movie_path, class: 'btn btn-success pull-right' %></h1>

<table class="table table-striped table-bordered table-hover table-condensed table-scrollable">
  <thead>
    <tr>
      <th>Imagen</th>
      <th>Nombre</th>
      <th>Director</th>
      <th>Categoría</th>
      <th>Fecha de Estreno</th>
      <th>Estatus</th>
      <th>Rentas</th>
      <th>Acciones</th>
    </tr>
  </thead>

  <tbody>
    <% @movies.each do |movie| %>
      <tr>
        <td><%= image_tag movie.image(:thumb), class: 'img-responsive table-column-image' %></td>
        <td><%= movie.name %></td>
        <td><%= movie.director %></td>
        <td><%= movie.category.name %></td>
        <td><%= movie.release_date %></td>
        <td>
          <% if movie.client.nil? %>
          <label class="label label-success">Disponible</label>
          <% else %>
            <label class="label label-danger">Rentada a <%= movie.client.name %></label>
          <% end %>
        <td><%= movie.rents %></td>
        <td>
          <%= link_to '<i class="fa fa-eye fa-lg"></i>'.html_safe, movie %>

          <% if movie.client.nil? %>
            <%= link_to '<i class="fa fa-film fa-lg"></i>'.html_safe, rent_movie_path(movie) %>
          <% else %>
            <%= link_to '<i class="fa fa-reply fa-lg"></i>'.html_safe, return_movie_path(movie), method: :post, data: { confirm: movie.client.name + ' retornará ésta película' } %>
          <% end %>

          <%= link_to '<i class="fa fa-pencil fa-lg"></i>'.html_safe, edit_movie_path(movie) %>
          <%= link_to '<i class="fa fa-trash fa-lg"></i>'.html_safe, movie, method: :delete, data: { confirm: 'Se eliminará ésta película' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/movies/new.html.erb
<div class="row">
  <div class="col-sm-12">
    <h1 class="page-header">Nueva Película</h1>
  </div>
</div>

<div class="row">
  <div class="col-sm-6">
    <div class="panel panel-default">
      <div class="panel-body">
        <%= render 'form', movie: @movie %>
      </div>
    </div>
  </div>
</div>

app/views/movies/rent.html.erb
<div class="row">
  <div class="col-sm-12">
    <h1 class="page-header">Rentar Película</h1>
  </div>
</div>

<div class="row">
  <div class="col-sm-6">
    <div class="panel panel-default">
      <div class="panel-body">
        <%= form_for @movie, :url => rent_movie_url(@movie), :method => :put do |f| %>
          <%= render 'application/form_errors', form: @movie %>

          <div class="form-group">
            <%= f.label :name, "Película", class: "control-label" %>
            <%= f.text_field :name, class: "form-control", :readonly => true, data: { validation: 'required' }  %>
          </div>

          <div class="form-group">
            <%= label_tag :client_id, "Cliente", class: "control-label" %>
            <%= f.collection_select :client_id, @clients, :id, :name, { include_blank: 'Seleccione un cliente', selected: (@movie.client.id unless @movie.client.nil?) }, { id: 'client-selector', class: 'form-control', data: { validation: 'required' } } %>
          </div>

          <div class="form-group">
            <%= f.submit "Guardar", class: "btn btn-primary" %>
          </div>
        <% end %>

      </div>
    </div>
  </div>
</div>

app/views/movies/show.html.erb
<div class="row">
  <div class="col-sm-4">
    <p>
      <strong>Nombre:</strong>
      <%= @movie.name %>
    </p>

    <p>
      <strong>Director:</strong>
      <%= @movie.director %>
    </p>

    <p>
      <strong>Categoría:</strong>
      <%= @movie.category.name %>
    </p>

    <p>
      <strong>Fecha de Estreno:</strong>
      <%= @movie.release_date %>
    </p>

    <% unless @movie.client.nil? %>
      <p>
        <strong>Cliente que la alquiló:</strong>
        <%= @movie.client.name %>
      </p>
    <% end %>

    <p>
      <strong>Rentas:</strong>
      <%= @movie.rents %>
    </p>
  </div>
  <div class="col-sm-3">
    <%= image_tag @movie.image(:medium), class: 'img-responsive' %>
  </div>
</div>

<%= link_to '<i class="fa fa-pencil fa-2x"></i>'.html_safe, edit_movie_path(@movie) %> |
<%= link_to '<i class="fa fa-arrow-circle-left fa-2x"></i>'.html_safe, movies_path %>