config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  # Users
  devise_for :users, controllers: { passwords: "passwords" }, skip: :registrations
  resources :users do
    get 'enable', on: :member
    get 'disable', on: :member
    get 'deleted', on: :collection
    get 'restore', on: :member
  end

  resources :clients

  resources :movies do
    post 'return', action: :return_movie, on: :member
    get 'rent', on: :member
    put 'rent', action: :update_rent, on: :member
  end
end

app/models/client.rb
class Client < ApplicationRecord

  has_many :movies

end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  add_breadcrumb "Inicio", :root_path
  add_breadcrumb "Clientes", :clients_path

  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.includes(:movies).order(name: :asc).all
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
    add_breadcrumb @client.name
    add_breadcrumb "Detalles"
  end

  # GET /clients/new
  def new
    add_breadcrumb "Agregar"

    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
    add_breadcrumb @client.name
    add_breadcrumb "Editar"
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'El Cliente ha sido creado exitosamente.' }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'El Cliente ha sido actualizado exitosamente.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    if @client.movies.count == 0
      @client.destroy
      respond_to do |format|
        format.html { redirect_to clients_url, notice: 'El Cliente ha sido eliminado exitosamente.' }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { redirect_to client_url, notice: 'El Cliente tiene peliculas rentadas.' }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def client_params
      params.require(:client).permit(:name, :email)
    end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_form.html.erb
<%= form_for(client) do |f| %>
  <%= render 'application/form_errors', form: client %>

  <div class="form-group">
    <%= f.label :name, "Nombre", class: "control-label" %>
    <%= f.text_field :name, class: "form-control", data: { validation: 'required' }  %>
  </div>

  <div class="form-group">
    <%= f.label :email, "Email", class: "control-label" %>
    <%= f.text_field :email, class: "form-control", data: { validation: 'required|email' }  %>
  </div>

  <div class="form-group">
    <%= f.submit "Guardar", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<div class="row">
  <div class="col-sm-12">
    <h1 class="page-header">Editar Cliente</h1>
  </div>
</div>

<div class="row">
  <div class="col-sm-6">
    <div class="panel panel-default">
      <div class="panel-body">
        <%= render 'form', client: @client %>
      </div>
    </div>
  </div>
</div>

app/views/clients/index.html.erb
<h1>Clientes <%= link_to 'Agregar', new_client_path, class: 'btn btn-success pull-right' %></h1>

<table class="table table-striped table-bordered table-hover table-condensed table-scrollable">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Email</th>
      <th>Rentas Actuales</th>
      <th>Rentas</th>
      <th>Acciones</th>
    </tr>
  </thead>

  <tbody >
    <% @clients.each do |client| %>
      <tr>
        <td><%= client.name %></td>
        <td><%= client.email %></td>
        <td>
          <% if client.movies.count > 0 %>
            <%= (client.movies.map { |movie| movie.name }).join(', ') %>
          <% else %>
            <em class="text-muted">Sin Rentas</em>
          <% end %>
        </td>
        <td><%= client.rents %></td>
        <td>
          <%= link_to '<i class="fa fa-eye fa-lg"></i>'.html_safe, client %>
          <%= link_to '<i class="fa fa-pencil fa-lg"></i>'.html_safe, edit_client_path(client) %>
          <%= link_to '<i class="fa fa-trash fa-lg"></i>'.html_safe, client, method: :delete, data: { confirm: 'Se eliminará éste cliente' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/clients/new.html.erb
<div class="row">
  <div class="col-sm-12">
    <h1 class="page-header">Nuevo Cliente</h1>
  </div>
</div>

<div class="row">
  <div class="col-sm-6">
    <div class="panel panel-default">
      <div class="panel-body">
        <%= render 'form', client: @client %>
      </div>
    </div>
  </div>
</div>

app/views/clients/show.html.erb
<p>
  <strong>Nombre:</strong>
  <%= @client.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @client.email %>
</p>

<% if @client.movies.count > 0 %>
  <p>
    <strong>Rentas Actuales:</strong>
    <%= (@client.movies.map { |movie| movie.name }).join(', ') %>
  </p>
<% end %>

<p>
  <strong>Rentas:</strong>
  <%= @client.rents %>
</p>

<%= link_to '<i class="fa fa-pencil fa-2x"></i>'.html_safe, edit_client_path(@client) %> |
<%= link_to '<i class="fa fa-arrow-circle-left fa-2x"></i>'.html_safe, clients_path %>