config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  # Users
  devise_for :users, controllers: { passwords: "passwords" }, skip: :registrations
  resources :users do
    get 'enable', on: :member
    get 'disable', on: :member
    get 'deleted', on: :collection
    get 'restore', on: :member
  end

  resources :clients

  resources :movies do
    post 'return', action: :return_movie, on: :member
    get 'rent', on: :member
    put 'rent', action: :update_rent, on: :member
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path, alert: "No tienes permiso para acceder a esta sección."
  end

  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_in, keys: [:username])
      devise_parameter_sanitizer.permit(:account_update, keys: [:username])
    end
end

app/views/application/_breadcrumb.html.erb
<% if user_signed_in? %>
  <ol class="breadcrumb">
    <%= render_breadcrumbs tag: :li, separator: "" %>
  </ol>
<% end %>

app/views/application/_favicon.html.erb
<link rel="apple-touch-icon" sizes="180x180" href="<%= asset_path 'assets/favicon/favicon.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= asset_path 'assets/favicon/favicon.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= asset_path 'assets/favicon/favicon.png' %>">
<link rel="manifest" href="<%= asset_path 'assets/favicon/manifest.json' %>">
<link rel="mask-icon" href="<%= asset_path 'assets/favicon/safari-pinned-tab.svg' %>" color="#5bbad5">
<link rel="shortcut icon" href="<%= asset_path 'assets/favicon/favicon.png' %>">
<meta name="msapplication-config" content="<%= asset_path 'assets/favicon/browserconfig.xml' %>">
<meta name="theme-color" content="#ffffff">

app/views/application/_form_errors.html.erb
<% if form.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(form.errors.count, "error") %> han prohibido que éste registro sea guardado:</h2>

    <ul>
      <% form.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/application/_nav.html.erb
<div class="navbar-header">
  <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
      <span class="sr-only">Abrir menú</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
  </button>

  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag 'logo-movies.png', style: 'height:40px; width:auto;' %>
  <% end %>
</div>

<% if user_signed_in? %>
  <ul class="nav navbar-top-links navbar-right">
    <li id="userDropdown" class="dropdown">
      <a class="dropdown-toggle" data-toggle="dropdown" href="#">
        <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
      </a>
      <ul class="dropdown-menu dropdown-user">
        <li>
          <%= link_to destroy_user_session_path, method: :delete do %>
            <i class="fa fa-sign-out fa-fw"></i> Cerrar sesión
          <% end %>
        </li>
      </ul>
    </li>
  </ul>
<% end %>

<%= render partial: 'sidebar' %>

app/views/application/_notices_and_alerts.html.erb
<div id="notification-wrapper">
  <% if notice %>
    <div class="alert alert-info alert-dismissible fade in" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Cerrar"><span aria-hidden="true">×</span></button>
      <%= notice %>
    </div>
  <% end %>

  <% if alert %>
    <div class="alert alert-danger alert-dismissible fade in" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
      <%= alert %>
    </div>
  <% end %>
</div>

app/views/application/_sidebar.html.erb
<div class="navbar-default sidebar" role="navigation">
  <div class="sidebar-nav navbar-collapse">
    <ul class="nav" id="side-menu">
      <% if user_signed_in? %>
        <li>
          <%= link_to root_path do %>
            <i class="fa fa-dashboard fa-fw"></i> Inicio
          <% end %>
        </li>
        <li>
          <%= link_to movies_url do %>
            <i class="fa fa-film fa-fw"></i> Peliculas
          <% end %>
        </li>
        <li>
          <%= link_to clients_url do %>
            <i class="fa fa-user fa-fw"></i> Clientes
          <% end %>
        </li>
      <% else %>

      <% end %>
    </ul>
  </div>
</div>